=== lemonycap/JavaExternal/Task6/src/main/resources/data/XSDSchemeForCandies.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema"
			targetNamespace = "http://example.com/candies"
			xmlns = "http://example.com/candies"
		    elementFormDefault="qualified">
			<xs:element  name = "candies">
				<xs:complexType>
					<xs:sequence>
						<xs:element name = "candy"
								 type = "candy"
								 minOccurs = "3"
								 maxOccurs = "unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:complexType name = "candy">
				<xs:sequence>
					<xs:element name = "name" type = "xs:string"/>
					<xs:element name = "energy" type = "xs:string" />
					<xs:element name = "type" type = "xs:string" />
					<xs:element name = "ingredients" type = "Ingredients"/>
					<xs:element name = "value" type = "Value"/>
					<xs:element name = "product_owner" type = "xs:string"/>
				</xs:sequence>
				<xs:attribute name = "productName" type = "xs:string" use = "required"/>
				<xs:attribute name = "filling" use = "optional" default = "no filling">
					<xs:simpleType>
						<xs:restriction base = "xs:string">
							<xs:enumeration value = "no filling"></xs:enumeration>
							<xs:enumeration value = "cacao"></xs:enumeration>
							<xs:enumeration value = "hazelnut"></xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:complexType>
				<xs:complexType name = "Ingredients">
					<xs:sequence>
						<xs:element name = "water" type = "xs:string"/>
						<xs:element name = "sugar" type = "xs:string"/>
						<xs:element name = "fructose" type = "xs:string"/>
						<xs:element name = "vaniline" type = "xs:string"/>
						<xs:element name = "chocolate_type" type = "xs:string"/>
					</xs:sequence>
				</xs:complexType>
				<xs:complexType name = "Value">
					<xs:sequence>
						<xs:element name = "proteins" type = "xs:string"/>
						<xs:element name = "fats" type = "xs:string"/>
						<xs:element name = "carbs" type = "xs:string"/>
					</xs:sequence>
				</xs:complexType>
				
	</xs:schema>

=== lemonycap/JavaExternal/Task6/src/main/resources/data/Candies.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<?xml-stylesheet type="text/xsl" href="candiesXSL.xsl"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xmlns:ns="http://www.example.com/candies"
			 xsi:schemaLocation="http://www.example.com/candies XSDSchemeForCandies.xsd">
	<candy productName = "Caramel candy" filling = "no filling">
		<name> Mechta </name>
		<energy> 30 ccal </energy>
		<type> caramel </type>
		<ingredients>
			<water>100 ml</water>
			<sugar> 20 mg </sugar>
			<fructose> 30 mg </fructose>
			<vaniline> 3 mg </vaniline>
			<chocolate_type> no chocolate </chocolate_type>
		</ingredients>
		<value>
			<proteins> 3 g </proteins>
			<fats> 2 g </fats>
			<carbs> 3 g </carbs>
		</value>
		<product_owner> Rot Front </product_owner>
	</candy>
	<candy productName = "Chocolate candy" filling = "cacao">
		<name> Romashka </name>
		<energy> 40 ccal </energy>
		<type> chocolate </type>
		<ingredients>
			<water>100 ml</water>
			<sugar> 30 mg </sugar>
			<fructose> 20 mg </fructose>
			<vaniline> 5 mg </vaniline>
			<chocolate_type> milk </chocolate_type>
		</ingredients>
		<value>
			<proteins> 4 g </proteins>
			<fats> 5 g </fats>
			<carbs> 2 g </carbs>
		</value>
		<product_owner> Roshen </product_owner>
	</candy>
	<candy productName = "Toffee candy" filling = "hazelnut">
	<name> Mu-mu </name>
		<energy> 10 ccal </energy>
		<type> toffee </type>
		<ingredients>
			<water>50 ml</water>
			<sugar> 30 mg </sugar>
			<fructose> 20 mg </fructose>
			<vaniline> 1 mg </vaniline>
			<chocolate_type> no chocolate </chocolate_type>
		</ingredients>
		<value>
			<proteins> 2 g </proteins>
			<fats> 1 g </fats>
			<carbs> 1 g </carbs>
		</value>
		<product_owner> Krupska </product_owner>
	</candy>
</candies>

=== lemonycap/JavaExternal/Task6/target/classes/data/Candies.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xmlns:ns="http://www.example.com/candies"
			 xsi:schemaLocation="http://www.example.com/candies XSDSchemeForCandies.xsd">
	<candy productName = "Caramel candy" filling = "no filling">
		<name> Mechta </name>
		<energy> 30 ccal </energy>
		<type> caramel </type>
		<ingredients>
			<water>100 ml</water>
			<sugar> 20 mg </sugar>
			<fructose> 30 mg </fructose>
			<vaniline> 3 mg </vaniline>
			<chocolate-type> no chocolate </chocolate-type>
		</ingredients>
		<value>
			<proteins> 3 g </proteins>
			<fats> 2 g </fats>
			<carbs> 3 g </carbs>
		</value>
		<product-owner> Rot Front </product-owner>
	</candy>
	<candy productName = "Chocolate candy" filling = "cacao">
		<name> Romashka </name>
		<energy> 40 ccal </energy>
		<type> chocolate </type>
		<ingredients>
			<water>100 ml</water>
			<sugar> 30 mg </sugar>
			<fructose> 20 mg </fructose>
			<vaniline> 5 mg </vaniline>
			<chocolate-type> milk </chocolate-type>
		</ingredients>
		<value>
			<proteins> 4 g </proteins>
			<fats> 5 g </fats>
			<carbs> 2 g </carbs>
		</value>
		<product-owner> Roshen </product-owner>
	</candy>
	<candy productName = "Toffee candy" filling = "hazelnut">
	<name> Mu-mu </name>
		<energy> 10 ccal </energy>
		<type> toffee </type>
		<ingredients>
			<water>50 ml</water>
			<sugar> 30 mg </sugar>
			<fructose> 20 mg </fructose>
			<vaniline> 1 mg </vaniline>
			<chocolate-type> no chocolate </chocolate-type>
		</ingredients>
		<value>
			<proteins> 2 g </proteins>
			<fats> 1 g </fats>
			<carbs> 1 g </carbs>
		</value>
		<product-owner> Krupska </product-owner>
	</candy>
</candies>
